name: Deploying app on WF
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update
        sudo apt install ffmpeg
    - name: Run app
      env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_UN: ${{ secrets.BOT_UN }}
      continue-on-error: true
      run: |
        python -m main
        
